---

- name: An example add nodes to a pool
  hosts: bigip
  connection: local

  vars:
    validate_certs: no
    username: admin
    password: admin

  tasks:
    - name: Add the iApp
      bigip_iapp_template:
        content: "{{ lookup('file', '../files/f5.http.v1.2.0rc4.tmpl') }}"
        state: present
        password: "{{ password }}"
        server: "{{ ansible_host }}"
        user: "{{ username }}"
        validate_certs: "{{ validate_certs }}"

    - name: Add the iApp Service
      bigip_iapp_service:
        name: http-iapp1-v2
        template: f5.http.v1.2.0rc4
        password: "{{ password }}"
        server: "{{ ansible_host }}"
        validate_certs: "{{ validate_certs }}"
        state: present
        user: "{{ username }}"
        parameters:
          lists:
            - name: irules__irules
              value: ""
          tables:
            - name: basic__snatpool_members
            - name: net__snatpool_members
            - name: optimizations__hosts
            - name: pool__hosts
              columnNames:
                - name
              rows:
                - row:
                    - internal.company.bar
            - name: pool__members
              columnNames:
                - addr
                - port
                - connection_limit
              rows:
                - row:
                    - ""
                    - 80
                    - 0
            - name: server_pools__servers
          variables:
            - name: var__vs_address
              value: 1.1.1.1
            - name: pm__apache_servers_for_http
              value: 2.2.2.1:80
            - name: pm__apache_servers_for_https
              value: 2.2.2.2:80
            - name: client__http_compression
              value: "/#create_new#"
            - name: monitor__monitor
              value: "/#create_new#"
            - name: monitor__uri
              value: "/"
            - name: net__client_mode
              value: wan
            - name: net__server_mode
              value: lan
            - name: pool__addr
              value: 10.10.10.10
            - name: pool__pool_to_use
              value: "/#create_new#"
            - name: pool__port
              value: 80
            - name: ssl__mode
              value: no_ssl
            - name: ssl_encryption_questions__advanced
              value: no
            - name: ssl_encryption_questions__help
              value: hide
