---

- name: An example add nodes to a pool
  hosts: bigip
  connection: local

  vars:
    validate_certs: no
    username: admin
    password: admin

  tasks:
    - name: Create Web server VIP
      bigip_virtual_server:
        description: webserver-vip
        address: 10.1.1.100
        name: webserver-vip-1
        pool: web-servers
        port: 443
        snat: Automap
        all_profiles:
          - http
          - clientssl

        password: "{{ password }}"
        server: "{{ ansible_host }}"
        user: "{{ username }}"
        validate_certs: "{{ validate_certs }}"
