---

- name: Change root Password
  hosts: bigip
  connection: local
  gather_facts: no

  vars:
    validate_certs: no
    username: admin
    password: admin

  tasks:
  - name: Change root password
    bigip_user:
      user: "{{ username }}"
      password: "{{ password }}"
      server: "{{ ansible_host }}"
      validate_certs: "{{ validate_certs }}"
      username_credential: "root"
      password_credential: ChangedPassword1234
#      update_password: on_create
      state: present
