---

- name: Change the root user's password
  hosts: ltm 
  gather_facts: no
  connection: local

  environment:
    F5_SERVER: "{{ ansible_host }}"
    F5_USER: "admin"
    F5_PASSWORD: "admin"
    F5_VALIDATE_CERTS: no

  tasks:
    - name: Change the root user's password
      bigip_user:
        username_credential: root
        password_credential: root
        state: present




