---

- name: create Tacac auth 
  hosts: ltm 
  gather_facts: no
  connection: local

  environment:
    F5_SERVER: "{{ ansible_host }}"
    F5_USER: "admin"
    F5_PASSWORD: "admin"
    F5_VALIDATE_CERTS: no

  tasks:
    - name: run show version on remote devices
      bigip_command:
       commands:  modify auth source type tacacs  
      run_once: true

