---

- name: Create iRule 
  hosts: ltm 
  gather_facts: no
  connection: local

  environment:
    F5_SERVER: "{{ ansible_host }}"
    F5_USER: "admin"
    F5_PASSWORD: "admin"
    F5_VALIDATE_CERTS: no


  tasks:
    - name: Create iRule in LTM
      bigip_irule:
        content: "{{ lookup('template', 'httpredirect.tcl') }}"
        module: ltm
        name: httpredirect 
      run_once: true
