---

- name: Restoration the BIGIPs to default with just management IP
  hosts: ltm
  gather_facts: no
  connection: local

  environment:
    F5_SERVER: "{{ ansible_host }}"
    F5_USER: "admin"
    F5_PASSWORD: "admin"
    F5_VALIDATE_CERTS: no

  tasks:
    - name: Provision LTM at "nominal" level
      bigip_provision:
        module: ltm
      tags: provision

