---

- name: Set the banner for the SSHD service from a file
  hosts: ltm 
  gather_facts: no
  connection: local

  environment:
    F5_SERVER: "{{ ansible_host }}"
    F5_USER: "admin"
    F5_PASSWORD: "admin"
    F5_VALIDATE_CERTS: no

  tasks:
    - name: Set the banner for the SSHD service from a file
      bigip_device_sshd:
        allow: "{{ access }}"
        banner: "{{ banner }}" 
        banner_text: "{{ banner_text }}"
