---

- name: Create device trust 
  hosts: ltm 
  gather_facts: no
  connection: local

  environment:
    F5_SERVER: "{{ ansible_host }}"
    F5_USER: "admin"
    F5_PASSWORD: "admin"
    F5_VALIDATE_CERTS: no

  tasks:
    - name: Sync configuration from device to group using "{{ day1.sync_fail_name }}"
      bigip_configsync_action:
        device_group: "{{ day1.sync_fail_name }}"
        sync_device_to_group: yes
      run_once: true

