---

- name: Add 10 Virual server
  hosts: ltm 
  gather_facts: no
  connection: local

  environment:
    F5_SERVER: "{{ ansible_host }}"
    F5_USER: "admin"
    F5_PASSWORD: "admin"
    F5_VALIDATE_CERTS: no


  tasks:
    - name: Add 10 virtual server
      bigip_virtual_server:
        name: "vip{{ item }}"
        destination: "10.10.100.{{ item|int + 10 }}"
        port: 80
        pool: "pool{{ item }}"
        snat: Automap
        description: "Virtual Server vip{{ item }}"
        profiles:
          - http
      with_sequence: start=1 count=10
      run_once: true
